name: Build Client

on:
  workflow_dispatch:
    inputs:
      version:
        description: EZCA Client Version
        required: true
        default: '1.2.0'
  
env:
  GH_TOKEN: ${{ github.token }}
jobs:

  build-windows:
    name: Build client for Windows
    runs-on: windows-latest  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      - name: Authenticate with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.EZCA_CLIENT_DEPLOYER  }}
      - name: Install SignTool
        run: dotnet tool install --global  AzureSignTool
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Run Powershell Script 
        run: .\DotNetCertAuthSample\build.ps1
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: .\DotNetCertAuthSample\DotNetCertAuthSample\bin\Release\net10.0\win-x64\publish\EZCACertManager.exe

  build-macos:
    name: Build client for MacOS
    runs-on: macos-latest
    env:
      NOTARIZE_PASSWORD: "${{ secrets.MAC_DEV_PASSWORD }}"
      MAC_CERT_PASSWORD: "${{ secrets.MAC_CERT_PASSWORD }}"
      KEYCHAIN_PASSWORD: "${{ secrets.MAC_KEYCHAIN_PASSWORD }}"
      MAC_CERT_BASE64: "${{ secrets.MAC_CERT_BASE64 }}"
      TEAM_ID: ""
      APPLE_ID: ""
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          submodules: 'true'

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Create Keychain and Import Signing Certificate
        run: |
          export MAC_CERT_BASE64="$MAC_CERT_BASE64"
          export MAC_CERT_PASSWORD="$MAC_CERT_PASSWORD"
          export KEYCHAIN_PASSWORD="$KEYCHAIN_PASSWORD"
          export TEAM_ID="$TEAM_ID"
          export APPLE_ID="$APPLE_ID"
          chmod +x ./DotNetCertAuthSample/import-macos-cert.sh
          ./DotNetCertAuthSample/import-macos-cert.sh

      - name: Build, Sign, and Verify MacOS App
        working-directory: DotNetCertAuthSample
        run: |
          export NOTARIZE_PASSWORD="$NOTARIZE_PASSWORD"
          export TEAM_ID="$TEAM_ID"
          export APPLE_ID="$APPLE_ID"
          export SIGNING_IDENTITY="Developer ID Application: Keytos LLC ($TEAM_ID)"
          chmod +x ./build-macos.sh
          ./build-macos.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-binary
          path: ./DotNetCertAuthSample/DotNetCertAuthSample/bin/Release/net10.0/osx-arm64/publish/EZCACertManager

  build-linux:
    name: Build client for Linux (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'true'

      - name: Install other utilities
        run: sudo apt-get install -y dpkg moreutils

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: create deb
        working-directory: ./DotNetCertAuthSample
        run: VERSION="${{ inputs.version }}"  make -C .

      - name: rename deb
        working-directory: ./DotNetCertAuthSample
        run: mv ./EZCACertManager.deb ./EZCACertManager-${{ matrix.os }}.deb

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-binary-${{ matrix.os }}
          path: ./DotNetCertAuthSample/EZCACertManager-${{ matrix.os }}.deb

  create-release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-macos, build-linux]
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      # - name: Create GitHub Release
      #   run: gh release create ezca-client-v${{ inputs.version }} --title "Certificate Renewal Client v${{ inputs.version }}" --repo ${{ github.repository }}
      #
      # - name: Upload Windows Binary
      #   run: gh release upload ezca-client-v${{ inputs.version }} ./artifacts/windows-binary/EZCACertManager.exe --repo ${{ github.repository }}
      #
      # - name: Upload macOS Binary
      #   run: gh release upload ezca-client-v${{ inputs.version }} ./artifacts/macos-binary/EZCACertManager --repo ${{ github.repository }}
      #
      # - name: Upload Linux Binaries
      #   run: |
      #     gh release upload ezca-client-v${{ inputs.version }} ./artifacts/linux-binary-ubuntu-22.04/EZCACertManager-ubuntu-22.04.deb --repo ${{ github.repository }}
      #     gh release upload ezca-client-v${{ inputs.version }} ./artifacts/linux-binary-ubuntu-24.04/EZCACertManager-ubuntu-24.04.deb --repo ${{ github.repository }}
      # - name: Download all artifacts
      #   uses: actions/download-artifact@v4
      #   with:
      #     path: ./artifacts
      #
      # - name: Create GitHub Release
      #   run: gh release create ezca-client-v${{ inputs.version }} --title "Certificate Renewal Client v${{ inputs.version }}" --repo ${{ github.repository }}
      #
      # - name: Upload Windows Binary
      #   run: gh release upload ezca-client-v${{ inputs.version }} ./artifacts/windows-binary/EZCACertManager.exe --repo ${{ github.repository }}
      #
      # - name: Upload macOS Binary
      #   run: gh release upload ezca-client-v${{ inputs.version }} ./artifacts/macos-binary/EZCACertManager --repo ${{ github.repository }}
      #
      # - name: Upload Linux Binaries
      #   run: |
      #     gh release upload ezca-client-v${{ inputs.version }} ./artifacts/linux-binary-ubuntu-22.04/EZCACertManager-ubuntu-22.04.deb --repo ${{ github.repository }}
      #     gh release upload ezca-client-v${{ inputs.version }} ./artifacts/linux-binary-ubuntu-24.04/EZCACertManager-ubuntu-24.04.deb --repo ${{ github.repository }}
